### ISSUE TITLE
Падает при отправке сообщений в слак

### ISSUE THREAD

**Issue by diamtr** [MonkAlex/Slackbot-Kami-sama#18]
Вызов запроса
https://slack.apphb.com/general
с параметрами заканчивается 500 Internal Server Error

{"Message":"An error has occurred.","ExceptionMessage":"Error occured while posting message
'method_deprecated'","ExceptionType":"SlackConnector.Exceptions.CommunicationException","StackTrace":" at
SlackConnector.Connections.Clients.ResponseVerifier.VerifyResponse(StandardResponse response)\r\n at
SlackConnector.Connections.Clients.Channel.FlurlChannelClient.<GetChannels>d__17.MoveNext()\r\n--- End of stack trace
	from previous location where exception was thrown ---\r\n at
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at
	SlackConnector.SlackConnection.<GetChannels>d__54.MoveNext()\r\n--- End of stack trace from previous location where
		exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at
		System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at
		Slackbot.Kamisama.Bot.BotClient.<GetChannels>d__9.MoveNext() in D:\\temp\\z1odytig.znw\\input\\Slackbot
			Kami-sama\\Bot\\BotClient.cs:line 34\r\n--- End of stack trace from previous location where exception was
			thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at
			System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at
			Slackbot.Kamisama.Controllers.GeneralController.<Post>d__0.MoveNext() in
				D:\\temp\\z1odytig.znw\\input\\Slackbot Kami-sama\\Controllers\\GeneralController.cs:line 21\r\n--- End
				of stack trace from previous location where exception was thrown ---\r\n at
				System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at
				System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at
				System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack trace
					from previous location where exception was thrown ---\r\n at
					System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at
					System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n
					at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>
						d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown
						---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at
						System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
						task)\r\n at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n---
							End of stack trace from previous location where exception was thrown ---\r\n at
							System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at
							System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
							task)\r\n at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>
								d__1.MoveNext()"}

**Comment by MonkAlex** [comment]
https://github.com/noobot/SlackConnector/issues/96

Оформлено, но автор похоже не очень активен. Пора менять библиотеку или актуализировать эту.

**Comment by diamtr** [comment]
мб https://github.com/Inumedia/SlackAPI ?

**Comment by MonkAlex** [comment]
Запрос надо перепроверить, в #19 по идее должно было быть исправлено. Но я потестил только команды в чате.
